### ISSUE TITLE
Does work perfectly with Home Assistant

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/zwave-js-ui_ynh#27]
### Describe the bug

*The doc says that it was never tested with Home Assistant.*

### Context

Not relevant...

### Steps to reproduce

- Install Z-Wave package as usual
- Follow quick start instructions https://zwave-js.github.io/zwave-js-ui/#/getting-started/quick-start?id=minimum-settings
- Add an integration in Home Assistant, connect to localhost 3000 (default config)
- It works \o/

### Expected behavior

*Not known until now.*

**Comment by Krakinou** [comment]
Thanks for testing!

**Comment by Krakinou** [comment]
Thanks for testing!
